#!/bin/bash

cd ../..

instance=$(echo $1 | grep -oP "/home/gian/MECBA-Hyp/irace/Instances//\K.*")
#IFS='@' read -a array <<< "$instance"
problem=$instance
objectives=4

function="MultiArmedBandit"
#function="ChoiceFunction"

candidate=$2

alpha=1.0
beta=0.012

w=150
c=$3

evaluations=60000
population=300
crossover=0.95
mutation=0.02
executions=1
path="experiment/"
cfpath=$candidate$path

java -cp dist/MECBA-Hyp.jar hyperheuristics.main.NSGAIIHyperheuristicMain $population $evaluations $crossover $mutation $alpha $beta TwoPointsCrossover,MultiMaskCrossover,PMXCrossover SwapMutation,SimpleInsertionMutation $problem $function $w $c $objectives false $executions $cfpath
java -cp dist/MECBA-Hyp.jar hyperheuristics.main.CompareHypervolumes $executions $path $cfpath $cfpath $objectives $problem

aux="objectives/HYPERVOLUMES.txt"
output=$cfpath$objectives$aux
mecba=$(cat $output | grep -oP "MECBA PFknown: \K.*")
mab=$(cat $output | grep -oP "MultiArmedBandit PFknown: \K.*")
cf=$(cat $output | grep -oP "ChoiceFunction PFknown: \K.*")

mecba=${mecba/[eE]+*/*10^}
mab=${mab/[eE]+*/*10^}
cf=${cf/[eE]+*/*10^}

# EH MINIMIZACAO
best=$(echo "$mecba - $mab" | bc)
echo Best $best

rm -rf $cfpath
