#!/bin/bash

cd ../..

instance=$(echo $1 | grep -oP "/home/tux/MECBA-Hyp/irace/Instances//\K.*")
IFS='@' read -a array <<< "$instance"
problem=${array[0]}
objectives=${array[1]}

#function="MultiArmedBandit"
function="ChoiceFunction"

candidate=$2

alpha=1.0
beta=$3

w=12000
c=7

echo $problem $1 >> problem.log

evaluations=60000
population=300
crossover=0.95
mutation=0.02
executions=1
path="experiment/"
cfpath=$candidate$path

java -cp dist/MECBA-Hyp.jar hyperheuristics.main.NSGAIIHyperheuristicMain $population $evaluations $crossover $mutation $alpha $beta TwoPointsCrossover,MultiMaskCrossover,PMXCrossover SwapMutation,SimpleInsertionMutation $problem $function $w $c $objectives false $executions $cfpath
java -cp dist/MECBA-Hyp.jar hyperheuristics.main.CompareHypervolumes $executions $cfpath $path $cfpath $objectives $problem

aux="objectives/HYPERVOLUMES.txt"
output=$cfpath$objectives$aux
mecba=$(cat $output | grep -oP "MECBA PFknown: \K.*")
mab=$(cat $output | grep -oP "MultiArmedBandit PFknown: \K.*")
cf=$(cat $output | grep -oP "ChoiceFunction PFknown: \K.*")

mecba=${mecba/[eE]+*/*10^}
mab=${mab/[eE]+*/*10^}
cf=${cf/[eE]+*/*10^}

# EH MINIMIZACAO
best=$(echo "$mecba - $cf" | bc)
echo Best $best

